/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as DayNRouteImport } from './routes/day.$n'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const DayNRoute = DayNRouteImport.update({
  id: '/day/$n',
  path: '/day/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/squad': typeof SquadRoute
  '/day/$n': typeof DayNRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/squad': typeof SquadRoute
  '/day/$n': typeof DayNRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/squad': typeof SquadRoute
  '/day/$n': typeof DayNRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/history'
    | '/leaderboard'
    | '/onboarding'
    | '/portfolio'
    | '/settings'
    | '/squad'
    | '/day/$n'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/history'
    | '/leaderboard'
    | '/onboarding'
    | '/portfolio'
    | '/settings'
    | '/squad'
    | '/day/$n'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/history'
    | '/leaderboard'
    | '/onboarding'
    | '/portfolio'
    | '/settings'
    | '/squad'
    | '/day/$n'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
  SquadRoute: typeof SquadRoute
  DayNRoute: typeof DayNRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$n': {
      id: '/day/$n'
      path: '/day/$n'
      fullPath: '/day/$n'
      preLoaderRoute: typeof DayNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
  SquadRoute: SquadRoute,
  DayNRoute: DayNRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
